from enum import Enum


class ProductCategory(Enum):
    TEXTBOOKS = 'TEXTBOOKS'
    STUDY_GUIDES = 'STUDY_GUIDES'
    ELECTRONICS = 'ELECTRONICS'
    LAPTOPS_TABLETS = 'LAPTOPS & TABLETS'
    CALCULATORS = 'CALCULATORS'
    CHARGERS = 'CHARGERS'
    LAB_MATERIALS = 'LAB MATERIALS'
    NOTEBOOKS = 'NOTEBOOKS'
    ART_DESIGN = 'ART & DESIGN'
    ROBOTIC_KITS = 'ROBOTIC KITS'
    THREE_D_PRINTING = '3D PRINTING'
    UNIFORMS = 'UNIFORMS'
    SPORTS = 'SPORTS'
    MUSICAL_INSTRUMENTS = 'MUSICAL INSTRUMENTS'
